trigger:
- main

stages:

- stage: BuildAndTest
  displayName: 'Build and Test'

  jobs:
  - job: Build
    displayName: 'Build and Test Application'

    pool:
      vmImage: 'ubuntu-latest'

    steps:

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.12'
      displayName: 'Install Python'

    - script: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pytest
      displayName: 'Install dependencies and run tests'
